/**
 * Extra bots seed — 90 additional verified profiles for swipe testing.
 * These bots are NOT pre-matched, so they appear in the discover feed.
 * Run: npm run db:extra-bots
 */
import { inArray, eq } from 'drizzle-orm';
import { db } from '../lib/db';
import { colleges, users } from './schema';
import { hashPassword } from '../utils/hash';
import { BOT_EMAIL_DOMAIN } from '../lib/bots';

type Goal = 'MARRIAGE' | 'LONGTERM' | 'CASUAL' | 'EXPLORING';
type Gender = 'MAN' | 'WOMAN';

interface BotDef {
  firstName: string; lastName: string; gender: Gender; photo: number;
  domain: string; major: string; age: number; dob: string;
  gpa: number; sat: number; bio: string;
  interests: string[]; values: string[]; goal: Goal;
}

function email(b: BotDef) {
  return `${b.firstName.toLowerCase()}.${b.lastName.toLowerCase()}${BOT_EMAIL_DOMAIN}`;
}

// ── 45 women ──────────────────────────────────────────────────────────────────
const women: BotDef[] = [
  { firstName:'Zoe', lastName:'Anderson', gender:'WOMAN', photo:1, domain:'brown.edu', major:'Psychology', age:21, dob:'2003-04-12', gpa:3.82, sat:1490, bio:"Psychology at Brown with a side obsession in behavioral economics. I read papers for fun and I'm not sorry about it. Looking for someone with genuine opinions.", interests:['Reading','Running','Coffee','Film','Yoga'], values:['Curiosity','Empathy','Growth'], goal:'LONGTERM' },
  { firstName:'Lily', lastName:'Park', gender:'WOMAN', photo:2, domain:'nyu.edu', major:'Theater & Film', age:22, dob:'2002-09-18', gpa:3.71, sat:1440, bio:"NYU film student who takes the subway everywhere and has seen every Criterion release. I write scripts at 1am and eat good food whenever possible.", interests:['Film','Writing','Art','Travel','Music'], values:['Creativity','Authenticity','Humor'], goal:'LONGTERM' },
  { firstName:'Isabella', lastName:'Torres', gender:'WOMAN', photo:3, domain:'usc.edu', major:'Business Administration', age:22, dob:'2002-06-07', gpa:3.78, sat:1460, bio:"USC business with a startup on the side. Ambitious without the arrogance. I work hard and play harder — usually outdoors.", interests:['Startups','Hiking','Finance','Travel','Fashion'], values:['Ambition','Loyalty','Independence'], goal:'LONGTERM' },
  { firstName:'Ava', lastName:'Johnson', gender:'WOMAN', photo:4, domain:'vanderbilt.edu', major:'Nursing', age:21, dob:'2003-01-25', gpa:3.88, sat:1430, bio:"Future nurse at Vanderbilt. I care deeply about people and it shows. Also obsessed with vintage music and farmers markets.", interests:['Volunteering','Music','Cooking','Health','Reading'], values:['Compassion','Kindness','Family'], goal:'LONGTERM' },
  { firstName:'Mia', lastName:'Chen', gender:'WOMAN', photo:5, domain:'caltech.edu', major:'Physics', age:20, dob:'2004-11-03', gpa:3.96, sat:1580, bio:"Physics at Caltech. Yes, really. No, I don't know how to explain what I study at parties. Yes, I've tried.", interests:['Science','Chess','Hiking','Cooking','Reading'], values:['Curiosity','Integrity','Excellence'], goal:'EXPLORING' },
  { firstName:'Chloe', lastName:'Kim', gender:'WOMAN', photo:6, domain:'cmu.edu', major:'Human-Computer Interaction', age:22, dob:'2002-03-14', gpa:3.85, sat:1530, bio:"CMU HCI — I design things people actually want to use. Outside of class I make ceramics, which is the exact opposite of digital work and that's the point.", interests:['Design','Coding','Art','Photography','Coffee'], values:['Creativity','Curiosity','Growth'], goal:'LONGTERM' },
  { firstName:'Natalie', lastName:'Brooks', gender:'WOMAN', photo:7, domain:'georgetown.edu', major:'International Relations', age:22, dob:'2002-07-29', gpa:3.79, sat:1500, bio:"IR at Georgetown with a focus on Sub-Saharan Africa. I've lived in three countries and have opinions about all of them.", interests:['Politics','Languages','Travel','Volunteering','Wine'], values:['Justice','Empathy','Curiosity'], goal:'LONGTERM' },
  { firstName:'Hannah', lastName:'Lee', gender:'WOMAN', photo:8, domain:'virginia.edu', major:'Economics', age:21, dob:'2003-05-16', gpa:3.83, sat:1510, bio:"Economics at UVA. I love markets, mountains, and people who can hold a real conversation. Not necessarily in that order.", interests:['Economics','Hiking','Running','Reading','Cooking'], values:['Ambition','Authenticity','Humor'], goal:'LONGTERM' },
  { firstName:'Abigail', lastName:'Wright', gender:'WOMAN', photo:9, domain:'unc.edu', major:'Public Health', age:23, dob:'2001-10-09', gpa:3.76, sat:1450, bio:"Public health at UNC because systems-level thinking matters more than individual choices. I argue about health policy recreationally.", interests:['Volunteering','Yoga','Politics','Reading','Film'], values:['Compassion','Justice','Growth'], goal:'LONGTERM' },
  { firstName:'Evelyn', lastName:'Martinez', gender:'WOMAN', photo:10, domain:'rice.edu', major:'Architecture', age:22, dob:'2002-08-22', gpa:3.81, sat:1490, bio:"Architecture at Rice. Perpetually sleep-deprived and always opinionated about public space. I sketch on everything.", interests:['Architecture','Art','Travel','Coffee','Music'], values:['Creativity','Excellence','Integrity'], goal:'LONGTERM' },
  { firstName:'Sophia', lastName:'Liu', gender:'WOMAN', photo:11, domain:'jhu.edu', major:'Biomedical Engineering', age:21, dob:'2003-02-28', gpa:3.91, sat:1560, bio:"Biomedical engineering at Hopkins, working on drug delivery research. I contain multitudes — lab bench by day, terrible cook by night.", interests:['Science','Cooking','Running','Reading','Fitness'], values:['Excellence','Curiosity','Health'], goal:'LONGTERM' },
  { firstName:'Grace', lastName:'Williams', gender:'WOMAN', photo:12, domain:'duke.edu', major:'Biology', age:20, dob:'2004-06-30', gpa:3.89, sat:1540, bio:"Bio at Duke on the pre-med track. I study hard, run often, and somehow still find time to bake sourdough. It's about priorities.", interests:['Science','Running','Cooking','Yoga','Volunteering'], values:['Ambition','Kindness','Health'], goal:'LONGTERM' },
  { firstName:'Lauren', lastName:'Thompson', gender:'WOMAN', photo:13, domain:'northwestern.edu', major:'Journalism', age:22, dob:'2002-04-11', gpa:3.74, sat:1470, bio:"Journalism at Northwestern with a media criticism habit I can't kick. I write about technology and culture and have thoughts about both.", interests:['Writing','Politics','Film','Coffee','Travel'], values:['Integrity','Curiosity','Authenticity'], goal:'LONGTERM' },
  { firstName:'Ella', lastName:'Robinson', gender:'WOMAN', photo:14, domain:'cornell.edu', major:'Hotel Administration', age:21, dob:'2003-09-05', gpa:3.77, sat:1420, bio:"Hospitality at Cornell's hotel school. I genuinely care about how spaces make people feel — restaurants, hotels, apartments, first dates.", interests:['Cooking','Travel','Wine','Art','Fashion'], values:['Kindness','Creativity','Excellence'], goal:'LONGTERM' },
  { firstName:'Zoey', lastName:'Clark', gender:'WOMAN', photo:15, domain:'umich.edu', major:'Business + CS', age:22, dob:'2002-01-19', gpa:3.84, sat:1510, bio:"Michigan Ross + CS. I want to build things AND understand the business case for them. Weekends are for hiking and cooking elaborate meals for anyone willing to eat them.", interests:['Startups','Hiking','Coding','Finance','Cooking'], values:['Ambition','Loyalty','Growth'], goal:'LONGTERM' },
  { firstName:'Aubrey', lastName:'Lewis', gender:'WOMAN', photo:16, domain:'dartmouth.edu', major:'Environmental Studies', age:21, dob:'2003-07-24', gpa:3.73, sat:1460, bio:"Environmental studies at Dartmouth because somebody has to care about the next fifty years. Trail runner and poor-quality wildlife photographer.", interests:['Nature','Running','Photography','Volunteering','Reading'], values:['Integrity','Adventure','Compassion'], goal:'EXPLORING' },
  { firstName:'Aria', lastName:'Walker', gender:'WOMAN', photo:17, domain:'emory.edu', major:'Biology', age:22, dob:'2002-12-08', gpa:3.87, sat:1520, bio:"Biology at Emory with a genuine interest in infectious disease. I spend a lot of time in labs and I somehow still enjoy it, which tells you everything.", interests:['Science','Yoga','Cooking','Music','Reading'], values:['Curiosity','Health','Growth'], goal:'LONGTERM' },
  { firstName:'Nora', lastName:'Hall', gender:'WOMAN', photo:18, domain:'wustl.edu', major:'Social Work', age:23, dob:'2001-03-17', gpa:3.69, sat:1400, bio:"Social work at WashU. I believe the most important work is the kind that doesn't scale. Finding people who believe the same thing.", interests:['Volunteering','Reading','Film','Coffee','Yoga'], values:['Empathy','Justice','Compassion'], goal:'LONGTERM' },
  { firstName:'Riley', lastName:'Young', gender:'WOMAN', photo:19, domain:'tufts.edu', major:'International Relations', age:21, dob:'2003-06-14', gpa:3.81, sat:1480, bio:"IR at Tufts with a focus on East Asian security. I debate foreign policy for fun and have an opinion on everything, which I've been told is both charming and exhausting.", interests:['Politics','Languages','Travel','Running','Writing'], values:['Curiosity','Integrity','Ambition'], goal:'LONGTERM' },
  { firstName:'Madison', lastName:'Harris', gender:'WOMAN', photo:20, domain:'bu.edu', major:'Communications', age:22, dob:'2002-10-02', gpa:3.68, sat:1380, bio:"Comms at BU — PR, branding, and storytelling are my thing. I'm strategic but I lead with warmth. Also: I make really good pasta.", interests:['Fashion','Coffee','Travel','Photography','Film'], values:['Creativity','Humor','Authenticity'], goal:'LONGTERM' },
  { firstName:'Charlotte', lastName:'White', gender:'WOMAN', photo:21, domain:'tulane.edu', major:'Pre-Medicine', age:21, dob:'2003-08-27', gpa:3.86, sat:1510, bio:"Pre-med at Tulane navigating New Orleans life between study sessions. The city is relentless and I love it. Looking for someone with that same energy.", interests:['Music','Cooking','Running','Science','Travel'], values:['Ambition','Family','Health'], goal:'LONGTERM' },
  { firstName:'Layla', lastName:'Scott', gender:'WOMAN', photo:22, domain:'utexas.edu', major:'Computer Science', age:22, dob:'2002-05-10', gpa:3.83, sat:1500, bio:"CS at UT Austin + two internships in. I build backend systems and have no patience for bad UI. Big on hiking in the Hill Country whenever Austin lets me breathe.", interests:['Coding','Hiking','Startups','Music','Coffee'], values:['Ambition','Curiosity','Authenticity'], goal:'LONGTERM' },
  { firstName:'Penelope', lastName:'Green', gender:'WOMAN', photo:23, domain:'uchicago.edu', major:'Philosophy', age:21, dob:'2003-11-21', gpa:3.92, sat:1550, bio:"Philosophy at UChicago. I read Wittgenstein for fun and actually enjoy it. Looking for someone who has a rich inner life and knows how to communicate it.", interests:['Philosophy','Reading','Chess','Writing','Film'], values:['Integrity','Curiosity','Excellence'], goal:'LONGTERM' },
  { firstName:'Stella', lastName:'Baker', gender:'WOMAN', photo:24, domain:'purdue.edu', major:'Industrial Engineering', age:22, dob:'2002-07-06', gpa:3.77, sat:1460, bio:"Engineering at Purdue — I optimize systems and somehow also manage to cook elaborate Sunday dinners. Both require the same brain, honestly.", interests:['Fitness','Cooking','Science','Running','Nature'], values:['Excellence','Loyalty','Health'], goal:'LONGTERM' },
  { firstName:'Violet', lastName:'Adams', gender:'WOMAN', photo:25, domain:'psu.edu', major:'Broadcast Journalism', age:21, dob:'2003-04-03', gpa:3.65, sat:1380, bio:"Broadcast journalism at Penn State. I want to tell stories that matter. Podcast addict, reluctant morning person, enthusiastic about good food.", interests:['Writing','Film','Politics','Coffee','Travel'], values:['Integrity','Creativity','Authenticity'], goal:'EXPLORING' },
  { firstName:'Luna', lastName:'Nelson', gender:'WOMAN', photo:27, domain:'uw.edu', major:'Environmental Science', age:22, dob:'2002-02-14', gpa:3.78, sat:1440, bio:"Environmental science at UW with a Pacific Northwest problem — I can't imagine living anywhere without mountains within an hour. Trail running and bad birdwatching.", interests:['Nature','Running','Photography','Science','Yoga'], values:['Adventure','Compassion','Growth'], goal:'EXPLORING' },
  { firstName:'Scarlett', lastName:'Carter', gender:'WOMAN', photo:28, domain:'osu.edu', major:'Finance', age:23, dob:'2001-09-15', gpa:3.74, sat:1430, bio:"Finance at Ohio State. I like markets, data, and people who say what they mean. Currently interning at a fund and actually enjoying it, which surprises me.", interests:['Finance','Running','Travel','Reading','Fitness'], values:['Ambition','Loyalty','Success'], goal:'LONGTERM' },
  { firstName:'Hazel', lastName:'Mitchell', gender:'WOMAN', photo:29, domain:'northeastern.edu', major:'Graphic Design', age:21, dob:'2003-07-19', gpa:3.71, sat:1400, bio:"Design co-op at a Boston agency, study at Northeastern. I think deeply about how things look and I can tell when something is off-brand from across the room.", interests:['Design','Art','Coffee','Photography','Fashion'], values:['Creativity','Authenticity','Excellence'], goal:'LONGTERM' },
  { firstName:'Aurora', lastName:'Roberts', gender:'WOMAN', photo:30, domain:'gwu.edu', major:'Political Science', age:22, dob:'2002-11-30', gpa:3.79, sat:1470, bio:"PoliSci at GWU, surrounded by DC energy but trying to stay sane. I intern on the Hill and have learned that idealism and pragmatism aren't mutually exclusive.", interests:['Politics','Running','Film','Languages','Writing'], values:['Justice','Integrity','Ambition'], goal:'LONGTERM' },
  { firstName:'Ellie', lastName:'Turner', gender:'WOMAN', photo:31, domain:'gatech.edu', major:'Computer Science', age:21, dob:'2003-08-08', gpa:3.88, sat:1540, bio:"CS at Georgia Tech on the AI/ML track. I research during the week and rock climb on weekends. The problem-solving transfers, weirdly.", interests:['Coding','Fitness','Science','Hiking','Music'], values:['Excellence','Curiosity','Growth'], goal:'LONGTERM' },
  { firstName:'Cora', lastName:'Phillips', gender:'WOMAN', photo:33, domain:'illinois.edu', major:'Statistics', age:22, dob:'2002-03-25', gpa:3.81, sat:1490, bio:"Statistics at UIUC. I find patterns in things and I'm comfortable with uncertainty, which is either a career strength or a personality trait. Maybe both.", interests:['Science','Reading','Chess','Cooking','Film'], values:['Curiosity','Integrity','Humor'], goal:'LONGTERM' },
  { firstName:'Piper', lastName:'Campbell', gender:'WOMAN', photo:34, domain:'wfu.edu', major:'Marketing', age:21, dob:'2003-05-07', gpa:3.69, sat:1390, bio:"Marketing at Wake Forest with a focus on brand strategy. I think good taste is underrated. Also: yoga, farmers markets, bad reality TV unironically.", interests:['Fashion','Yoga','Art','Coffee','Travel'], values:['Creativity','Humor','Authenticity'], goal:'LONGTERM' },
  { firstName:'Naomi', lastName:'Evans', gender:'WOMAN', photo:35, domain:'ufl.edu', major:'Psychology', age:22, dob:'2002-01-31', gpa:3.75, sat:1420, bio:"Psychology at Florida with a focus on adolescent development. Beach person but also a reader. I care about things deeply, which I've decided to lean into.", interests:['Volunteering','Reading','Yoga','Music','Film'], values:['Empathy','Kindness','Compassion'], goal:'LONGTERM' },
  { firstName:'Camille', lastName:'Edwards', gender:'WOMAN', photo:36, domain:'nd.edu', major:'Pre-Law', age:22, dob:'2002-10-23', gpa:3.84, sat:1520, bio:"Pre-law at Notre Dame and I actually love constitutional law, which is a rare thing to say sincerely. I debate and I mean it — but I listen first.", interests:['Law','Running','Reading','Philosophy','Travel'], values:['Justice','Integrity','Ambition'], goal:'LONGTERM' },
  { firstName:'Vivienne', lastName:'Collins', gender:'WOMAN', photo:37, domain:'columbia.edu', major:'English Literature', age:23, dob:'2001-06-05', gpa:3.76, sat:1480, bio:"English lit at Columbia. I read everything and have opinions about most of it. Looking for someone who reads — anything, I'm not a snob.", interests:['Reading','Writing','Art','Film','Coffee'], values:['Creativity','Authenticity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Iris', lastName:'Stewart', gender:'WOMAN', photo:38, domain:'harvard.edu', major:'Physics', age:21, dob:'2003-03-11', gpa:3.94, sat:1570, bio:"Physics at Harvard. I ask questions most people don't think to ask, which is either endearing or annoying depending on the day. Usually endearing.", interests:['Science','Chess','Reading','Hiking','Music'], values:['Curiosity','Excellence','Integrity'], goal:'EXPLORING' },
  { firstName:'Stella', lastName:'Morales', gender:'WOMAN', photo:39, domain:'stanford.edu', major:'Biology', age:22, dob:'2002-08-16', gpa:3.89, sat:1550, bio:"Bio at Stanford on the neuro track. I do research, I hike, and I make really good tamales from my grandmother's recipe. Multitasking is my core competency.", interests:['Science','Hiking','Cooking','Yoga','Travel'], values:['Family','Curiosity','Health'], goal:'LONGTERM' },
  { firstName:'Faye', lastName:'Rivera', gender:'WOMAN', photo:40, domain:'brown.edu', major:'Art History', age:23, dob:'2001-12-01', gpa:3.68, sat:1410, bio:"Art history at Brown with a curatorial ambition. I can read a room — and a painting. NYC is where I'm headed. Looking for someone who appreciates beauty seriously.", interests:['Art','Film','Travel','Coffee','Fashion'], values:['Creativity','Authenticity','Excellence'], goal:'LONGTERM' },
  { firstName:'Celeste', lastName:'Murphy', gender:'WOMAN', photo:41, domain:'princeton.edu', major:'Neuroscience', age:21, dob:'2003-09-26', gpa:3.93, sat:1570, bio:"Neuroscience at Princeton. I study consciousness which is simultaneously the most and least practical thing possible. I also run and make good playlists.", interests:['Science','Running','Music','Reading','Philosophy'], values:['Curiosity','Excellence','Integrity'], goal:'LONGTERM' },
  { firstName:'Willow', lastName:'Cooper', gender:'WOMAN', photo:42, domain:'yale.edu', major:'Theater Studies', age:22, dob:'2002-05-31', gpa:3.72, sat:1450, bio:"Theater at Yale — directing, not acting. I think about storytelling constantly, including in real life. I am excellent at listening.", interests:['Theater','Writing','Film','Art','Reading'], values:['Creativity','Authenticity','Empathy'], goal:'LONGTERM' },
  { firstName:'Adelaide', lastName:'Howard', gender:'WOMAN', photo:43, domain:'upenn.edu', major:'Finance', age:21, dob:'2003-07-08', gpa:3.86, sat:1530, bio:"Wharton finance. Yes, I know what that sounds like. No, I'm not who you're imagining. I'm competitive at work and genuinely kind in real life — compatible, I promise.", interests:['Finance','Tennis','Travel','Cooking','Reading'], values:['Ambition','Integrity','Loyalty'], goal:'LONGTERM' },
  { firstName:'Sabrina', lastName:'Ward', gender:'WOMAN', photo:45, domain:'cmu.edu', major:'Design', age:22, dob:'2002-04-22', gpa:3.79, sat:1470, bio:"Design at CMU. I can tell within seconds if something is designed well or not, which makes grocery shopping oddly stressful. Otherwise I'm very easygoing.", interests:['Design','Art','Coffee','Photography','Music'], values:['Creativity','Humor','Excellence'], goal:'LONGTERM' },
  { firstName:'Beatrice', lastName:'Reed', gender:'WOMAN', photo:46, domain:'ucla.edu', major:'Film Production', age:23, dob:'2001-11-14', gpa:3.73, sat:1440, bio:"Film production at UCLA. I've made three short films and they're getting progressively better. I see narrative everywhere including in the person across from me right now.", interests:['Film','Writing','Photography','Travel','Art'], values:['Creativity','Authenticity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Rosalind', lastName:'Fleming', gender:'WOMAN', photo:47, domain:'berkeley.edu', major:'Environmental Science', age:22, dob:'2002-06-19', gpa:3.82, sat:1490, bio:"Environmental science at Berkeley with a water policy focus. Trail running and poor-quality birding on weekends. I will drag you outdoors eventually.", interests:['Nature','Running','Science','Hiking','Yoga'], values:['Adventure','Integrity','Compassion'], goal:'EXPLORING' },
  { firstName:'Margot', lastName:'Gray', gender:'WOMAN', photo:48, domain:'umich.edu', major:'Architecture', age:21, dob:'2003-10-17', gpa:3.78, sat:1480, bio:"Architecture at Michigan Taubman. I think about how buildings make people feel and I take that seriously. Also: very strong opinions about coffee shops.", interests:['Architecture','Design','Travel','Coffee','Photography'], values:['Creativity','Excellence','Curiosity'], goal:'LONGTERM' },
];

// ── 45 men ────────────────────────────────────────────────────────────────────
const men: BotDef[] = [
  { firstName:'Liam', lastName:'Cooper', gender:'MAN', photo:1, domain:'harvard.edu', major:'Government', age:22, dob:'2002-07-15', gpa:3.88, sat:1550, bio:"Government at Harvard with a constitutional law fixation. I argue positions I don't believe to stress-test them, which is either great or a terrible habit.", interests:['Politics','Running','Philosophy','Reading','Wine'], values:['Integrity','Curiosity','Ambition'], goal:'LONGTERM' },
  { firstName:'Noah', lastName:'Martinez', gender:'MAN', photo:2, domain:'stanford.edu', major:'Physics', age:21, dob:'2003-02-28', gpa:3.93, sat:1570, bio:"Physics at Stanford. I think about the universe at scales that make most things feel unimportant, but somehow that makes me enjoy the small stuff more.", interests:['Science','Chess','Hiking','Music','Reading'], values:['Curiosity','Excellence','Humor'], goal:'LONGTERM' },
  { firstName:'Mason', lastName:'Thompson', gender:'MAN', photo:3, domain:'mit.edu', major:'Electrical Engineering', age:22, dob:'2002-11-04', gpa:3.89, sat:1560, bio:"EE at MIT. I design circuits and somehow also make good conversation — the two require completely different parts of the brain. Proud of both.", interests:['Science','Coding','Cycling','Cooking','Music'], values:['Excellence','Integrity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Elijah', lastName:'Anderson', gender:'MAN', photo:4, domain:'yale.edu', major:'Pre-Law', age:23, dob:'2001-08-21', gpa:3.82, sat:1520, bio:"Political theory at Yale on the law school track. I believe in institutions and I also believe they need reforming — simultaneously, without contradiction.", interests:['Law','Philosophy','Running','Reading','Travel'], values:['Justice','Integrity','Ambition'], goal:'LONGTERM' },
  { firstName:'Oliver', lastName:'Davis', gender:'MAN', photo:5, domain:'princeton.edu', major:'Economics', age:21, dob:'2003-05-10', gpa:3.9, sat:1560, bio:"Economics at Princeton. I model things for class and occasionally for fun, which I've been told is concerning but I think is charming.", interests:['Economics','Running','Chess','Travel','Cooking'], values:['Curiosity','Excellence','Humor'], goal:'LONGTERM' },
  { firstName:'Jacob', lastName:'Wilson', gender:'MAN', photo:6, domain:'columbia.edu', major:'Finance', age:22, dob:'2002-03-07', gpa:3.81, sat:1510, bio:"Finance at Columbia with a genuine interest in emerging markets. I've lived in three countries and I think that's done more for me than any class.", interests:['Finance','Travel','Languages','Running','Film'], values:['Ambition','Curiosity','Authenticity'], goal:'LONGTERM' },
  { firstName:'William', lastName:'Taylor', gender:'MAN', photo:7, domain:'upenn.edu', major:'Marketing', age:22, dob:'2002-09-24', gpa:3.74, sat:1470, bio:"Wharton marketing — the creative side, not the quantitative side. I'm brand-minded, people-oriented, and genuinely curious about what makes things resonate.", interests:['Startups','Design','Travel','Music','Coffee'], values:['Creativity','Authenticity','Ambition'], goal:'LONGTERM' },
  { firstName:'James', lastName:'Brown', gender:'MAN', photo:8, domain:'duke.edu', major:'Pre-Medicine', age:21, dob:'2003-06-13', gpa:3.87, sat:1530, bio:"Pre-med at Duke who actually reads the research behind clinical decisions. I take medicine seriously and everything else at about a 7/10.", interests:['Science','Basketball','Cooking','Reading','Fitness'], values:['Integrity','Ambition','Compassion'], goal:'LONGTERM' },
  { firstName:'Henry', lastName:'Jackson', gender:'MAN', photo:9, domain:'northwestern.edu', major:'Journalism', age:22, dob:'2002-01-29', gpa:3.76, sat:1480, bio:"Journalism at Medill with a longform writing focus. I care about truth in reporting and I'm learning to also care about truth in personal conversations.", interests:['Writing','Politics','Film','Coffee','Travel'], values:['Integrity','Curiosity','Authenticity'], goal:'LONGTERM' },
  { firstName:'Sebastian', lastName:'White', gender:'MAN', photo:10, domain:'dartmouth.edu', major:'Engineering', age:21, dob:'2003-10-17', gpa:3.79, sat:1490, bio:"Engineering at Dartmouth. I can explain quantum tunneling and I can also bake bread — these are my two most impressive skills and I'm comfortable with that.", interests:['Science','Cooking','Hiking','Chess','Music'], values:['Curiosity','Humor','Excellence'], goal:'LONGTERM' },
  { firstName:'Jack', lastName:'Harris', gender:'MAN', photo:11, domain:'brown.edu', major:'Philosophy', age:23, dob:'2001-07-08', gpa:3.75, sat:1460, bio:"Philosophy at Brown because the questions matter even when there are no answers. I argue as a sport and apologize genuinely when I go too far.", interests:['Philosophy','Reading','Film','Coffee','Running'], values:['Curiosity','Integrity','Humor'], goal:'EXPLORING' },
  { firstName:'Luke', lastName:'Martin', gender:'MAN', photo:12, domain:'cornell.edu', major:'Architecture', age:22, dob:'2002-04-19', gpa:3.83, sat:1500, bio:"Architecture at Cornell AAP. I think about cities the way most people think about people — as living, evolving systems. Also I'm a coffee snob and I stand by it.", interests:['Architecture','Design','Photography','Travel','Coffee'], values:['Creativity','Excellence','Authenticity'], goal:'LONGTERM' },
  { firstName:'Benjamin', lastName:'Garcia', gender:'MAN', photo:13, domain:'vanderbilt.edu', major:'Psychology', age:21, dob:'2003-09-02', gpa:3.78, sat:1450, bio:"Psychology at Vanderbilt with a focus on decision-making. I'm fascinated by why people do what they do — including myself, which is ongoing work.", interests:['Science','Music','Running','Reading','Cooking'], values:['Empathy','Curiosity','Growth'], goal:'LONGTERM' },
  { firstName:'Wyatt', lastName:'Miller', gender:'MAN', photo:14, domain:'rice.edu', major:'Music & Computer Science', age:22, dob:'2002-12-11', gpa:3.84, sat:1510, bio:"Music + CS double at Rice. I write algorithms and also write songs, which have more in common than people realize. Houston is underrated — fight me.", interests:['Music','Coding','Jazz','Photography','Coffee'], values:['Creativity','Excellence','Curiosity'], goal:'LONGTERM' },
  { firstName:'Carter', lastName:'Moore', gender:'MAN', photo:15, domain:'wustl.edu', major:'Business', age:23, dob:'2001-03-06', gpa:3.76, sat:1460, bio:"Business at WashU Olin with a venture focus. I think about what doesn't exist yet. On weekends I switch off entirely, which takes practice but I'm getting better.", interests:['Startups','Finance','Fitness','Travel','Film'], values:['Ambition','Loyalty','Growth'], goal:'LONGTERM' },
  { firstName:'Caden', lastName:'Taylor', gender:'MAN', photo:16, domain:'nd.edu', major:'International Relations', age:22, dob:'2002-06-25', gpa:3.8, sat:1490, bio:"IR at Notre Dame with a focus on Middle East policy. I speak Arabic at a conversational level and have thoughts about geopolitics that I try to keep civil at dinner.", interests:['Politics','Languages','Travel','Running','Philosophy'], values:['Curiosity','Integrity','Justice'], goal:'LONGTERM' },
  { firstName:'Julian', lastName:'Anderson', gender:'MAN', photo:17, domain:'georgetown.edu', major:'Political Economy', age:21, dob:'2003-01-15', gpa:3.81, sat:1500, bio:"Political economy at Georgetown. I care about how power and markets interact and I've been told I explain it well, which I've decided to believe.", interests:['Politics','Economics','Reading','Running','Film'], values:['Justice','Ambition','Curiosity'], goal:'LONGTERM' },
  { firstName:'Declan', lastName:'Walker', gender:'MAN', photo:18, domain:'emory.edu', major:'Pre-Medicine', age:22, dob:'2002-08-03', gpa:3.86, sat:1520, bio:"Pre-med at Emory doing research on neuroinflammation. I cook to decompress. I actually read the papers I cite, which apparently makes me unusual.", interests:['Science','Cooking','Running','Reading','Music'], values:['Integrity','Compassion','Excellence'], goal:'LONGTERM' },
  { firstName:'Gabriel', lastName:'Young', gender:'MAN', photo:19, domain:'cmu.edu', major:'Computer Science', age:21, dob:'2003-04-29', gpa:3.91, sat:1560, bio:"CS at CMU on the systems track. I build low-level things most people never think about and I find that oddly satisfying. Also: decent basketball game.", interests:['Coding','Basketball','Music','Chess','Science'], values:['Excellence','Curiosity','Humor'], goal:'LONGTERM' },
  { firstName:'Santiago', lastName:'Lee', gender:'MAN', photo:20, domain:'berkeley.edu', major:'Civil Engineering', age:22, dob:'2002-02-17', gpa:3.79, sat:1480, bio:"Civil engineering at Berkeley with a focus on sustainable infrastructure. I care about the built environment and I also care about spending time in the natural one.", interests:['Engineering','Hiking','Cycling','Cooking','Travel'], values:['Adventure','Integrity','Compassion'], goal:'LONGTERM' },
  { firstName:'Mateo', lastName:'Reyes', gender:'MAN', photo:21, domain:'ucla.edu', major:'Film Production', age:23, dob:'2001-11-09', gpa:3.7, sat:1430, bio:"Film at UCLA. I've directed two shorts and I'm working on a feature script. I think about story structure in real life, which makes me either good to date or exhausting.", interests:['Film','Writing','Photography','Music','Travel'], values:['Creativity','Authenticity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Theodore', lastName:'Hill', gender:'MAN', photo:23, domain:'umich.edu', major:'Computer Science', age:21, dob:'2003-07-21', gpa:3.85, sat:1520, bio:"CS at Michigan with an ML focus. I'm building a startup on the side and I'm either going to make it or learn something very expensive. Both seem fine.", interests:['Coding','Startups','Running','Music','Coffee'], values:['Ambition','Curiosity','Growth'], goal:'LONGTERM' },
  { firstName:'Kai', lastName:'Robinson', gender:'MAN', photo:24, domain:'virginia.edu', major:'Physics', age:22, dob:'2002-10-05', gpa:3.88, sat:1540, bio:"Physics at UVA with a quantum computing interest. I ask questions constantly and I've accepted that about myself. Also an avid climber.", interests:['Science','Hiking','Chess','Reading','Fitness'], values:['Curiosity','Excellence','Authenticity'], goal:'EXPLORING' },
  { firstName:'Adrian', lastName:'Scott', gender:'MAN', photo:25, domain:'unc.edu', major:'Public Policy', age:23, dob:'2001-09-16', gpa:3.77, sat:1460, bio:"Public policy at UNC with a focus on education equity. I believe data and values belong in the same conversation. Soccer on weekends.", interests:['Politics','Soccer','Reading','Running','Volunteering'], values:['Justice','Compassion','Integrity'], goal:'LONGTERM' },
  { firstName:'Miles', lastName:'Green', gender:'MAN', photo:26, domain:'uchicago.edu', major:'Economics', age:21, dob:'2003-05-22', gpa:3.92, sat:1560, bio:"Economics at UChicago where everyone argues about everything and somehow becomes a better thinker. I've started doing it at dinner now and I regret nothing.", interests:['Economics','Philosophy','Chess','Reading','Film'], values:['Curiosity','Excellence','Integrity'], goal:'LONGTERM' },
  { firstName:'Remy', lastName:'Baker', gender:'MAN', photo:27, domain:'usc.edu', major:'Business', age:22, dob:'2002-03-30', gpa:3.75, sat:1450, bio:"Business at USC Marshall with a real estate interest. LA native so I'm either plugged in or completely spoiled — probably both. Hiking and surfing on weekends.", interests:['Finance','Hiking','Travel','Cooking','Startups'], values:['Ambition','Loyalty','Adventure'], goal:'LONGTERM' },
  { firstName:'Xavier', lastName:'Adams', gender:'MAN', photo:28, domain:'nyu.edu', major:'Music Composition', age:23, dob:'2001-07-13', gpa:3.69, sat:1400, bio:"Music composition at NYU Tisch. I score films, write piano pieces, and have a complicated relationship with silence. NYC is home and I'll fight about it.", interests:['Music','Jazz','Film','Art','Coffee'], values:['Creativity','Authenticity','Excellence'], goal:'EXPLORING' },
  { firstName:'Finn', lastName:'Nelson', gender:'MAN', photo:29, domain:'bu.edu', major:'Philosophy', age:22, dob:'2002-12-04', gpa:3.73, sat:1440, bio:"Philosophy at BU with a focus on ethics and technology. I think about what we owe each other in the age of AI, which sounds abstract but matters quite concretely.", interests:['Philosophy','Reading','Running','Chess','Coffee'], values:['Integrity','Curiosity','Justice'], goal:'LONGTERM' },
  { firstName:'Holden', lastName:'Carter', gender:'MAN', photo:30, domain:'tufts.edu', major:'Environmental Science', age:21, dob:'2003-08-28', gpa:3.76, sat:1450, bio:"Environmental science at Tufts with a policy focus. I believe solving climate requires people who can talk to both scientists and senators. Working on being that person.", interests:['Nature','Running','Reading','Politics','Travel'], values:['Integrity','Adventure','Compassion'], goal:'EXPLORING' },
  { firstName:'Rowan', lastName:'Mitchell', gender:'MAN', photo:31, domain:'tulane.edu', major:'Architecture', age:22, dob:'2002-06-08', gpa:3.78, sat:1470, bio:"Architecture at Tulane in New Orleans, which is the best possible city to study how buildings and culture interact. I have thoughts about adaptive reuse specifically.", interests:['Architecture','Music','Travel','Photography','Art'], values:['Creativity','Curiosity','Authenticity'], goal:'LONGTERM' },
  { firstName:'Silas', lastName:'Roberts', gender:'MAN', photo:33, domain:'utexas.edu', major:'Computer Science', age:21, dob:'2003-03-18', gpa:3.84, sat:1510, bio:"CS at UT Austin with a distributed systems focus. I care about building things that actually work at scale, which is harder than people think. Also a serious cyclist.", interests:['Coding','Cycling','Science','Music','Coffee'], values:['Excellence','Integrity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Beckett', lastName:'Turner', gender:'MAN', photo:34, domain:'psu.edu', major:'Pre-Medicine', age:22, dob:'2002-01-07', gpa:3.82, sat:1490, bio:"Pre-med at Penn State balancing research and coursework and somehow surviving. I cook to manage stress and I've gotten quite good at it under pressure.", interests:['Science','Cooking','Soccer','Reading','Fitness'], values:['Ambition','Compassion','Health'], goal:'LONGTERM' },
  { firstName:'Tobias', lastName:'Phillips', gender:'MAN', photo:35, domain:'uw.edu', major:'Data Science', age:23, dob:'2001-10-25', gpa:3.83, sat:1500, bio:"Data science at UW. I find patterns in large datasets and I've been told I do the same thing with people, which I prefer to think of as being observant.", interests:['Science','Coding','Cycling','Reading','Film'], values:['Curiosity','Integrity','Growth'], goal:'LONGTERM' },
  { firstName:'Roman', lastName:'Campbell', gender:'MAN', photo:36, domain:'osu.edu', major:'Finance', age:22, dob:'2002-09-11', gpa:3.74, sat:1440, bio:"Finance at Ohio State with an investment interest. I analyze companies for class and crypto for fun, which tells you something about my risk tolerance.", interests:['Finance','Basketball','Travel','Fitness','Music'], values:['Ambition','Loyalty','Success'], goal:'LONGTERM' },
  { firstName:'Dante', lastName:'Evans', gender:'MAN', photo:37, domain:'northeastern.edu', major:'Computer Science', age:21, dob:'2003-06-29', gpa:3.8, sat:1490, bio:"CS at Northeastern on co-op rotation at a robotics company. I'm either going to work on autonomous systems or start something — still figuring it out.", interests:['Coding','Startups','Fitness','Science','Music'], values:['Ambition','Curiosity','Growth'], goal:'LONGTERM' },
  { firstName:'Pascal', lastName:'Edwards', gender:'MAN', photo:38, domain:'gwu.edu', major:'International Relations', age:22, dob:'2002-04-14', gpa:3.78, sat:1470, bio:"IR at GWU, DC is the right city for this. I've interned at two think tanks and have learned that the gap between policy thinking and policy making is vast.", interests:['Politics','Languages','Running','Reading','Film'], values:['Justice','Integrity','Curiosity'], goal:'LONGTERM' },
  { firstName:'Dorian', lastName:'Collins', gender:'MAN', photo:39, domain:'gatech.edu', major:'Mechanical Engineering', age:21, dob:'2003-11-22', gpa:3.86, sat:1530, bio:"Mechanical engineering at Georgia Tech. I build physical things and think about energy systems. Rock climbing when I need to use my hands for something enjoyable.", interests:['Engineering','Hiking','Fitness','Science','Coffee'], values:['Excellence','Curiosity','Adventure'], goal:'LONGTERM' },
  { firstName:'Sterling', lastName:'Stewart', gender:'MAN', photo:40, domain:'illinois.edu', major:'Finance', age:22, dob:'2002-08-05', gpa:3.77, sat:1460, bio:"Finance at UIUC with a quantitative lean. I think markets are fascinating and occasionally irrational, which makes them more interesting. Also: avid tennis player.", interests:['Finance','Tennis','Economics','Reading','Fitness'], values:['Ambition','Excellence','Integrity'], goal:'LONGTERM' },
  { firstName:'Archer', lastName:'Murphy', gender:'MAN', photo:42, domain:'wfu.edu', major:'Marketing', age:21, dob:'2003-07-17', gpa:3.7, sat:1410, bio:"Marketing at Wake Forest with a brand strategy focus. I think about why people choose what they choose and I'm good at making things feel right.", interests:['Design','Startups','Travel','Coffee','Photography'], values:['Creativity','Authenticity','Humor'], goal:'LONGTERM' },
  { firstName:'Cedric', lastName:'Howard', gender:'MAN', photo:43, domain:'ufl.edu', major:'Marine Biology', age:23, dob:'2001-05-29', gpa:3.76, sat:1440, bio:"Marine biology at Florida. I dive for research and have seen things most people only see in documentaries. Also annoyingly good at trivia about the ocean.", interests:['Science','Nature','Hiking','Photography','Travel'], values:['Curiosity','Adventure','Compassion'], goal:'EXPLORING' },
  { firstName:'Jasper', lastName:'Ward', gender:'MAN', photo:44, domain:'jhu.edu', major:'Pre-Medicine', age:22, dob:'2002-02-20', gpa:3.89, sat:1550, bio:"Pre-med at Hopkins. I'm in labs constantly and I've somehow maintained a personality throughout. Music is what keeps me human during exam season.", interests:['Science','Music','Running','Reading','Cooking'], values:['Excellence','Integrity','Compassion'], goal:'LONGTERM' },
  { firstName:'Felix', lastName:'Reed', gender:'MAN', photo:45, domain:'caltech.edu', major:'Physics', age:21, dob:'2003-09-04', gpa:3.95, sat:1580, bio:"Physics at Caltech. I think about the nature of time and space for homework, which gives perspective on everything else. Looking for someone who finds that interesting not intimidating.", interests:['Science','Chess','Hiking','Reading','Music'], values:['Curiosity','Excellence','Humor'], goal:'EXPLORING' },
  { firstName:'Orion', lastName:'Fleming', gender:'MAN', photo:46, domain:'purdue.edu', major:'Aerospace Engineering', age:22, dob:'2002-07-11', gpa:3.83, sat:1510, bio:"Aerospace engineering at Purdue. I'm going to work on spacecraft and I've known this since I was eight, which either sounds impressive or concerning.", interests:['Science','Nature','Fitness','Chess','Running'], values:['Excellence','Curiosity','Adventure'], goal:'LONGTERM' },
  { firstName:'Callum', lastName:'Gray', gender:'MAN', photo:47, domain:'gatech.edu', major:'Computer Science', age:23, dob:'2001-04-16', gpa:3.81, sat:1500, bio:"CS at Georgia Tech focused on computer vision. I'm building a startup on the side and I'm at the stage where it's either going to work or teach me something worth knowing.", interests:['Coding','Startups','Cycling','Science','Coffee'], values:['Ambition','Integrity','Growth'], goal:'LONGTERM' },
  { firstName:'Nico', lastName:'Cooper', gender:'MAN', photo:48, domain:'yale.edu', major:'Art History', age:22, dob:'2002-11-27', gpa:3.73, sat:1450, bio:"Art history at Yale going into museum work. I can tell you more about Baroque painting than most people want to know. Looking for someone who'll let me anyway.", interests:['Art','Film','Travel','Reading','Photography'], values:['Creativity','Authenticity','Curiosity'], goal:'LONGTERM' },
];

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  console.log('🌱 Seeding 90 extra bot profiles...\n');

  const collegeRows = await db
    .select({ id: colleges.id, emailDomain: colleges.emailDomain })
    .from(colleges);
  const collegeByDomain = new Map(collegeRows.map((c) => [c.emailDomain, c.id]));

  if (collegeRows.length === 0) {
    console.error('❌ No colleges found. Run: npm run db:seed first.');
    process.exit(1);
  }

  const botPasswordHash = await hashPassword('BotApex1!');
  const allBots = [...women, ...men];
  let inserted = 0;
  let skipped = 0;

  for (const bot of allBots) {
    const collegeId = collegeByDomain.get(bot.domain) ?? null;
    const botEmail = email(bot);
    const genderPath = bot.gender === 'MAN' ? 'men' : 'women';

    const result = await db
      .insert(users)
      .values({
        email: botEmail,
        passwordHash: botPasswordHash,
        firstName: bot.firstName,
        lastName: bot.lastName,
        age: bot.age,
        dateOfBirth: bot.dob,
        gender: bot.gender,
        bio: bot.bio,
        major: bot.major,
        gpa: bot.gpa,
        sat: bot.sat,
        interests: bot.interests,
        values: bot.values,
        relationshipGoal: bot.goal,
        collegeId,
        profilePhotoUrl: `https://randomuser.me/api/portraits/${genderPath}/${bot.photo}.jpg`,
        verified: true,
        idVerified: true,
        onboardingComplete: true,
      })
      .onConflictDoNothing()
      .returning({ id: users.id });

    if (result.length > 0) {
      inserted++;
    } else {
      skipped++;
    }
  }

  console.log(`✅ Inserted ${inserted} new bot profiles`);
  if (skipped > 0) console.log(`   (${skipped} already existed — skipped)`);
  console.log('\n🎉 Extra bots seed complete!');
  console.log(`   These ${inserted} bots will appear in the discover feed for swiping.`);
  console.log('   They are NOT pre-matched — swipe to connect.\n');
  process.exit(0);
}

main().catch((err) => {
  console.error('❌ Extra bots seed failed:', err);
  process.exit(1);
});
